### ISSUE TITLE
Pipeline run error: minio.error.S3Error: S3 operation failed; code: AccessDenied, message: Access Denied, resource: /dsp-bucket-12024b1a-7c00-4419-8ea8-d37bd64d7c34?location=, request_id: ly8g7534-e7skx0-wtm, host_id: None

### ISSUE THREAD

**Issue by rbo** [cloud-native-robotz-hackathon/infrastructure#47]
```
Downloading file:///opt/app-root/bin/utils/bootstrapper.py
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0100 31398 100 31398 0 0 29.9M 0 --:--:-- --:--:-- --:--:-- 29.9M
Downloading file:///opt/app-root/bin/utils/requirements-elyra.txt
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0Warning: Failed to create the file requirements-elyra.txt: Permission denied
0 1462 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
curl: (23) Failure writing output to destination
Requirement already satisfied: packaging in /opt/app-root/lib/python3.9/site-packages (24.0)
[notice] A new release of pip available: 22.3.1 -> 24.1.1
[notice] To update, run: pip install --upgrade pip
[D 08:43:01.815] Parsing Arguments.....
[I 08:43:01.817] 'model-training-cpu':'data_ingestion' - starting operation
[I 08:43:01.880] 'model-training-cpu':'data_ingestion' - processing dependencies
[D 08:43:01.880] Starting new HTTP connection (1): s3.openshift-storage.svc:80
[D 08:43:01.902] http://s3.openshift-storage.svc:80 "GET /dsp-bucket-12024b1a-7c00-4419-8ea8-d37bd64d7c34?location= HTTP/1.1" 403 231
Traceback (most recent call last):
File "/opt/app-root/src/bootstrapper.py", line 746, in <module>
main()
File "/opt/app-root/src/bootstrapper.py", line 734, in main
file_op.process_dependencies()
File "/opt/app-root/src/bootstrapper.py", line 127, in process_dependencies
self.get_file_from_object_storage(archive_file)
File "/opt/app-root/src/bootstrapper.py", line 295, in get_file_from_object_storage
self.cos_client.fget_object(bucket_name=self.cos_bucket, object_name=object_to_get, file_path=file_to_get)
File "/opt/app-root/lib64/python3.9/site-packages/minio/api.py", line 1033, in fget_object
stat = self.stat_object(
File "/opt/app-root/lib64/python3.9/site-packages/minio/api.py", line 1859, in stat_object
response = self._execute(
File "/opt/app-root/lib64/python3.9/site-packages/minio/api.py", line 394, in _execute
region = self._get_region(bucket_name, None)
File "/opt/app-root/lib64/python3.9/site-packages/minio/api.py", line 461, in _get_region
response = self._url_open(
File "/opt/app-root/lib64/python3.9/site-packages/minio/api.py", line 380, in _url_open
raise response_error
minio.error.S3Error: S3 operation failed; code: AccessDenied, message: Access Denied, resource: /dsp-bucket-12024b1a-7c00-4419-8ea8-d37bd64d7c34?location=, request_id: ly8g7534-e7skx0-wtm, host_id: None
```

**Comment by rbo** [comment]
![image](https://github.com/cloud-native-robotz-hackathon/infrastructure/assets/36604/ef5cd9c3-1a58-4071-a371-0637dfd99163)

Problem is, pipeline inject bucket from dsp and workbench and that overwrites the access keys.
