### ISSUE TITLE
Containerize edge-hub at the robot

### ISSUE THREAD

**Issue by rbo** [cloud-native-robotz-hackathon/infrastructure#94]
check out branch containerized

```bash
# podman build -t quay.io/cloud-native-robotz-hackathon/edgecontroller:devel .
# podman run --user 0 --privileged --device /dev/spidev0.0 --device /dev/spidev0.1 --rm -ti quay.io/cloud-native-robotz-hackathon/edgecontroller:devel   
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
Loading library without distance sensor
/bin/sh: line 1: gpio: command not found
/bin/sh: line 1: gpio: command not found
/bin/sh: line 1: gpio: command not found
Traceback (most recent call last):
  File "/opt/app-root/src/server.py", line 14, in <module>
    GPG = gopigo3.GoPiGo3()
  File "/opt/app-root/lib64/python3.9/site-packages/gopigo3.py", line 231, in __init__
    raise FirmwareVersionError("GoPiGo3 firmware needs to be version %s but is currently version %s" \
gopigo3.FirmwareVersionError: GoPiGo3 firmware needs to be version 0.3.x but is currently version 1.0.0
root@terminator:~/edgecontroller# 
```

**Comment by rbo** [comment]
Might be related to #102

**Comment by rbo** [comment]
- Issue from @goetzrieger to run GoPiGo3 on non-Debian: https://github.com/DexterInd/GoPiGo3/issues/320
- API Spec: https://gopigo3.readthedocs.io/en/master/api-basic/easygopigo3.html#easygopigo3.EasyGoPiGo3.backward
- python behind: https://github.com/DexterInd/GoPiGo3/blob/master/Software/Python/gopigo3.py#L33
  - It use move the robots it use spidev: https://pypi.org/project/spidev/
  - pigpio is only used to set some settings: https://github.com/DexterInd/GoPiGo3/blob/b50cfce3eced2b8d97132b1eef58cd3606ec1025/Software/Python/gopigo3.py#L231-L235
- Hardware Port description: 
   - https://gopigo3.readthedocs.io/en/master/api-basic/structure.html#hardware-ports 
   - https://gopigo3.readthedocs.io/en/master/quickstart.html#getting-familiar-with-the-gopigo3

**Comment by rbo** [comment]
Booted fedora 41 with RoboCop
```
sudo dnf install libgpiod-utils python3-libgpiod
sudo gpiodetect
[sudo] password for rbohne:
gpiochip0 [pinctrl-bcm2711] (58 lines)
gpiochip1 [raspberrypi-exp-gpio] (8 lines)
sudo gpioinfo

gpiochip0 - 58 lines:
        line   0:       "ID_SDA"                input
        line   1:       "ID_SCL"                input
        line   2:       "SDA1"                  input
        line   3:       "SCL1"                  input
        line   4:       "GPIO_GCLK"             input
        line   5:       "GPIO5"                 input
        line   6:       "GPIO6"                 input
        line   7:       "SPI_CE1_N"             input
        line   8:       "SPI_CE0_N"             input
        line   9:       "SPI_MISO"              input
        line  10:       "SPI_MOSI"              input
        line  11:       "SPI_SCLK"              input
        line  12:       "GPIO12"                input
        line  13:       "GPIO13"                input
        line  14:       "TXD1"                  input
        line  15:       "RXD1"                  input
        line  16:       "GPIO16"                input
        line  17:       "GPIO17"                input
        line  18:       "GPIO18"                input
        line  19:       "GPIO19"                input
        line  20:       "GPIO20"                input
        line  21:       "GPIO21"                input
        line  22:       "GPIO22"                input
        line  23:       "GPIO23"                input
        line  24:       "GPIO24"                input
        line  25:       "GPIO25"                input
        line  26:       "GPIO26"                input
        line  27:       "GPIO27"                input
        line  28:       "RGMII_MDIO"            input
        line  29:       "RGMIO_MDC"             input
        line  30:       "CTS0"                  input
        line  31:       "RTS0"                  input
        line  32:       "TXD0"                  input
        line  33:       "RXD0"                  input
        line  34:       "SD1_CLK"               input
        line  35:       "SD1_CMD"               input
        line  36:       "SD1_DATA0"             input
        line  37:       "SD1_DATA1"             input
        line  38:       "SD1_DATA2"             input
        line  39:       "SD1_DATA3"             input
        line  40:       "PWM0_MISO"             input
        line  41:       "PWM1_MOSI"             input
        line  42:       "STATUS_LED_G_CLK"      output consumer="ACT"
        line  43:       "SPIFLASH_CE_N"         input
        line  44:       "SDA0"                  input
        line  45:       "SCL0"                  input
        line  46:       "RGMII_RXCLK"           input
        line  47:       "RGMII_RXCTL"           input
        line  48:       "RGMII_RXD0"            input
        line  49:       "RGMII_RXD1"            input
        line  50:       "RGMII_RXD2"            input
        line  51:       "RGMII_RXD3"            input
        line  52:       "RGMII_TXCLK"           input
        line  53:       "RGMII_TXCTL"           input
        line  54:       "RGMII_TXD0"            input
        line  55:       "RGMII_TXD1"            input
        line  56:       "RGMII_TXD2"            input
        line  57:       "RGMII_TXD3"            input
gpiochip1 - 8 lines:
        line   0:       "BT_ON"                 output consumer="shutdown"
        line   1:       "WL_ON"                 output active-low consumer="reset"
        line   2:       "PWR_LED_OFF"           output active-low consumer="PWR"
        line   3:       "GLOBAL_RESET"          output
        line   4:       "VDD_SD_IO_SEL"         output consumer="vdd-sd-io"
        line   5:       "CAM_GPIO"              output consumer="regulator-cam1"
        line   6:       "SD_PWR_ON"             output consumer="regulator-sd-vcc"
        line   7:       unnamed                 input

```

**Comment by rbo** [comment]
I compated the device tree on t-1000 (default os) and robocop (fedora)

`dtc -I fs /proc/device-tree > /tmp/t-1000.dtdump`

![Image](https://github.com/user-attachments/assets/718e305a-1606-4651-b761-f33e7396585f)


According to https://freeshell.de/less/post/fedorarpispi/

Looks like we have to patch the device tree...

**Comment by rbo** [comment]
raspberrypi kernel: https://github.com/raspberrypi/linux/blob/rpi-5.15.y/arch/arm/boot/dts/bcm2711-rpi-4-b.dts#L326-L346

vs upstream: https://github.com/torvalds/linux/blob/master/arch/arm/boot/dts/broadcom/bcm2711-rpi-4-b.dts `spidev0: spidev@0` is missing

**Comment by rbo** [comment]
Fedora IoT is enough topic, let's do not Hijack this issue: https://github.com/cloud-native-robotz-hackathon/infrastructure/issues/159
